# Generated by Django 4.2.6 on 2023-10-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('route_type', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('GPS_lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('GPS_lon', models.DecimalField(decimal_places=6, max_digits=10)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
