# Generated by Django 4.2.6 on 2023-10-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crag',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='crag',
            name='lon',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
