# Generated by Django 4.2.6 on 2023-11-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tick'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tick',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'name', 'crag'), name='unique ticks'),
        ),
    ]
